### ISSUE TITLE
KeyError: 'logs'

### ISSUE THREAD

**Issue by antmar904** [mbabinski/InsightIDR4Py#1]
Hi
I just started using this.

I am trying to run the example script for user authentication and I am receiving the following error:

`anthony@computer:~/IDR$ python3 TestLogSearch.py
Traceback (most recent call last):
  File "/home/anthony/IDR/TestLogSearch.py", line 9, in <module>
    groups = idr.QueryGroups(logset_name, query, time_range)
  File "/home/anthony/IDR/IDR4Py.py", line 112, in QueryGroups
    log_ids = ListLogIdsByLogSetName(logset_name)
  File "/home/anthony/IDR/IDR4Py.py", line 37, in ListLogIdsByLogSetName
    log_info = GetLogInfo()
  File "/home/anthony/IDR/IDR4Py.py", line 22, in GetLogInfo
    response = requests.get(log_mgmt_url, headers=headers).json()["logs"]
KeyError: 'logs'`

**Comment by mbabinski** [comment]
Hello! First, do you have the right region code? [This page](https://docs.rapid7.com/insight/product-apis/#supported-regions) lists the various region codes for the InsightIDR API endpoints. It may be necessary to adjust the region code in the script to account for your region. You can check your region following the instructions [here](https://docs.rapid7.com/insight/navigate-the-insight-platform/#check-your-data-region).

**Comment by antmar904** [comment]
Hi.
Should I include "https://" in the region code or "https://us.api.insight.rapid7.com/idr" ?

**Comment by antmar904** [comment]
ok sorry I changed the region code to "us3" and this is working now.
sorry for the mistake and great work on this!!

**Comment by mbabinski** [comment]
All good! Thanks for taking it for a spin. 🙂
