### ISSUE TITLE
Feature Request?

### ISSUE THREAD

**Issue by antmar904** [mbabinski/InsightIDR4Py#2]
Hi.
Any interest on adding capability to work with Investigations via Python with the API?

I am really enjoying your work with Log Search so thank you.

**Comment by mbabinski** [comment]
Hey thanks for the request, and sorry for the slow reply! I think this sounds like a great addition to InsightIDR4Py. I've just written to the folks at Rapid7 to request access to a development sandbox environment so I can continue the development of this tool. I will keep this issue open.

**Comment by mbabinski** [comment]
Hi @antmar90, just a heads up that I've added extensive capabilities to this project, including working with Investigations, saved queries, and threats. I've also added the project to the Python Package Index: https://pypi.org/project/InsightIDR4Py/. Check it out when you have a chance and let me know what you think!

**Comment by antmar904** [comment]
Awesome, ill be sure to check it out this week!

**Comment by antmar904** [comment]
would you be able to assist on setting up keyring in my Ubuntu WSL?
